# Generated by Django 2.2.2 on 2020-07-03 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='activity_period',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Task.Activity_times'),
        ),
    ]
