# Generated by Django 2.2.2 on 2020-07-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_auto_20200703_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_times',
            name='Login_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='activity_times',
            name='Logout_time',
            field=models.DateTimeField(),
        ),
    ]
